name: learn_dsa
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4
  cloud_firestore: ^5.4.4

  # cloudinary
  cloudinary_sdk: ^5.0.0+1
  http: ^1.2.2

  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  image_cropper: ^8.0.2
  cupertino_icons: ^1.0.8
  regexed_validator: ^2.0.0+1
  shared_preferences: ^2.3.2
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_logo.png
    - assets/images/array_photos/array_pink.png
    - assets/images/app_icon.png
    - assets/images/array_photos/connector_array.png
    - assets/images/array_photos/array_explanation.png
    - assets/images/dsa_shadow.png

    - assets/default_profile_picture.jpg

    - assets/navbar_icons/add.png
    - assets/navbar_icons/arrow.png
    - assets/navbar_icons/arrows.png
    - assets/navbar_icons/back.png
    - assets/navbar_icons/check-mark.png
    - assets/navbar_icons/writing.png
    - assets/navbar_icons/home.png
    - assets/navbar_icons/document.png